variables:
  CI_REPOSITORY_URL: "https://gitlab.minecraftslaves.duckdns.org/graphontext/graphontext-backend.git"

stages:
  - test
  - build.

test:
  stage: test
  image:
    name: gcr.io/kaniko-project/executor:v1.9.2-debug
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --no-push
  only:
    - merge_requests

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.2-debug
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:latest"
  only:
    - main
