db:
  jdbcUrl: "jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:graphontext}"
  username: ${DATABASE_USERNAME:graphontext}
  password: ${DATABASE_PASSWORD:graphontext}
  poolName: application

liquibase:
  changelog: "liquibase/changelog.yaml"

auth:
  token:
    secret: asdfSFS34wfsdfsdfSDSD32dfsddDDerQSNCK34SOWEK5354fdgdf4
    algorithm: HmacSHA256
    lifetime: 60

storage:
  directory: visualizations

httpClient:
  campaignsApi:
    url: https://not-working-api.ru
  businessOfferMappingsApi:
    url: https://not-working-api.ru